version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./interchat-27029-firebase-adminsdk-fbsvc-444e56fd92.json:/app/credentials/serviceAccountKey.json

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
